project:
  type: website
  output-dir: docs

website:
  title: "Radwan Azim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Final Project
        href: psci3200/final-project.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



